username = "GraphBot"
wiki = "https://en.wikipedia.org/"

[graph_task]
db_url = "mysql://s56792:{{password}}@tools.db.svc.wikimedia.cloud/s56792__graph"
search_category = "Category:Pages_with_graphs_to_be_ported_by_GraphBot"

[rfd_task]
wiki_replica_db_url = "mysql://s56792:{{password}}@enwiki.web.db.svc.wikimedia.cloud/enwiki_p"

[rpc]
host = "localhost"
port = 8000
path = "/RPC2"
